package com.example.newottapp.ui.util

//have put api data in a string for easy access
class apijson {
    val json1 = "{\"page\":{\"title\":\"RomanticComedy\",\"total-content-items\":\"54\",\"page-num\":\"1\",\"page-size\":\"20\",\"content-items\":{\"content\":[{\"name\":\"TheBirds\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster3.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster2.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster1.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster1.jpg\"}]}}}"
    val json2  = "{\"page\":{\"title\":\"RomanticComedy\",\"total-content-items\":\"54\",\"page-num\":\"2\",\"page-size\":\"20\",\"content-items\":{\"content\":[{\"name\":\"RearWindow\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster6.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster5.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster4.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster5.jpg\"}]}}}"
    val json3  = "{\"page\":{\"title\":\"RomanticComedy\",\"total-content-items\":\"27\",\"page-num\":\"3\",\"page-size\":\"14\",\"content-items\":{\"content\":[{\"name\":\"FamilyPot\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster8.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster7.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster8.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster7.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"poster8.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster7.jpg\"},{\"name\":\"TheBirdswithanExtraLongTitle\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"RearWindow\",\"poster-image\":\"poster9.jpg\"},{\"name\":\"TheBirds\",\"poster-image\":\"poster8.jpg\"},{\"name\":\"FamilyPot\",\"poster-image\":\"posterthatismissing.jpg\"}]}}}"

    val apijson = mutableListOf(json1,json2,json3);
}